alextube_practice0/alextube/alextube/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url('', include('social.apps.django_app.urls', namespace='social')),

    url(r'^', include("users.urls", namespace="users")),

    url(r'^posts/', include("posts.urls", namespace="posts")),
]

alextube_practice0/alextube/posts/urls.py
from django.conf.urls import url

from posts.views import *

urlpatterns = [
        url(r'^new/$', PostCreateView.as_view(), name="create"),
        url(r'^confirm/$', PostCreateConfirmView.as_view(), name="confirm"),
    ]

alextube_practice0/alextube/users/urls.py
from django.conf.urls import url

from users.views import *

urlpatterns = [
    url(r'^signup/$', SignupView.as_view(), name="signup"),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
        ]

alextube_practice0/alextube/posts/models/post.py
from django.db import models
from users.models import Users


class Post(models.Model):

    user = models.ForeignKey(Users)

    video_id = models.CharField(
            max_length=16,
    )

    video_original_title = models.CharField(
            max_length=256,
            blank=True,
            null=True,
    )
    
    title = models.CharField(
            max_length=256,
    )
    content = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
  
    def get_youtube_embed_url(self):
        from posts.utils import get_youtube_embed_url as get_youtube_embed_url_from_video_id
        return get_youtube_embed_url_from_video_id(self.video_id)
    youtube_embed_url = property(get_youtube_embed_url)

    def get_youtube_original_url(self):
        from posts.utils import get_youtube_original_url as get_youtube_original_url_from_video_id
        return get_youtube_original_url_from_video_id(self.video_id)
    youtube_original_url = property(get_youtube_original_url)
   
    def __str__(self):
        return self.title

alextube_practice0/alextube/users/models/users.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Users(AbstractUser):
    phonenumber=models.CharField(
            max_length=10,
            blank=True,
            null=True,
    )
    

alextube_practice0/alextube/posts/views/create.py
from django.views.generic import View
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
from posts.utils import youtube
from users.models import Users

class PostCreateView(View): 

    def get(self, request, *args, **kwargs):
        return render(
                request,
                "posts/new.html",
                context={},
        )

    def post(self, request, *args, **kwargs):
        title = request.POST.get("title")
        content = request.POST.get("content")
        video_id = request.POST.get("video_id")

        post = request.user.post_set.create(
                title=title,
                content=content,
                video_id=video_id,
        )

        return redirect(reverse("posts:create"))


class PostCreateConfirmView(View):
    
    def get(self, request, *args, **kwargs):
        return redirect(reverse("post:create"))
    
    def post(self, request, *args, **kwargs):
        video_id = request.POST.get("video_id")
        title = request.POST.get("title")
        content = request.POST.get("content")

        return render(
                request,
                "posts/confirm.html",
                context={
                    "title":title,
                    "content":content,
                    "video_id":video_id,

                    "youtube_original_url":youtube.get_youtube_original_url(video_id),
                    "youtube_embed_url":youtube.get_youtube_embed_url(video_id),
                    },
        )

alextube_practice0/alextube/users/views/login.py
from django.views.generic import View
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.conf import settings

class LoginView(View):
    
    def get(self, request, *args, **kwargs):
        return render(
                request,
                "users/login.html",
                context={},
        )
        
    def post(self, request, *args, **kwargs):
        username = request.POST.get("username")
        password = request.POST.get("password")

        next_url =  request.POST.get("next_url") or reverse("users:login")

        user = authenticate(
                username=username,
                password=password,
        )

        if user:
            login(request, user)
            messages.add_message(
                    request,
                    messages.SUCCESS,
                    settings.LOGIN_SUCCESS_MESSAGE,
            )
            return redirect(next_url)

        messages.add_message(
                request,
                messages.ERROR,
                settings.LOGIN_ERROR_MESSAGE,
        )
        return redirect(reverse("users:login"))

alextube_practice0/alextube/users/views/logout.py
from django.views.generic import View
from django.core.urlresolvers import reverse
from django.contrib.auth import logout
from django.contrib import messages
from django.shortcuts import redirect
from django.conf import settings


class LogoutView(View):

    def get(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(
                request,
                messages.SUCCESS,
                settings.LOGOUT_SUCCESS_MESSAGE,
        )
        return redirect(reverse("users:login"))

alextube_practice0/alextube/users/views/signup.py
from django.views.generic import View
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.conf import settings


class SignupView(View):
    
    def get(self, request, *args, **kwargs):
        return render(
                request,
                "users/signup.html",
                context={},
        )

    def post(self, request, *args, **kwargs):
        username = request.POST.get("username")
        password = request.POST.get("password")
        phonenumber = request.POST.get("phonenumber")

        user = get_user_model().objects.create_user(
                username=username,
                password=password,
                phonenumber=phonenumber,
        )

        messages.add_message(
                request,
                messages.SUCCESS,
                settings.SIGNUP_SUCCESS_MESSAGE,
        )

        return redirect(reverse("users:login"))

alextube_practice0/alextube/alextube/templates/base.html
{% load pipeline %}<!DOCTYPE html>
<html>
<head>
	{% stylesheet "alextube" %}
</head>
<body>
	{% include "partials/header.html" %}
	{% include "partials/messages.html" %}
	<section id="content">
	{% block content %}
	{% endblock %}
	</section>
	{% include "partials/footer.html" %}
</body>
</html>

alextube_practice0/alextube/alextube/templates/partials/footer.html
<footer>
	<h1>Footer</h1>
</footer>

alextube_practice0/alextube/alextube/templates/partials/header.html
<header>
	<h1>Header</h1>
	<ul>
		{% if request.user.is_authenticated %}
		<li><a href="{% url "users:logout" %}">Logout</a></li>
		{% else %}
                <li><a href="{% url "users:login" %}">Login</a></li>
		<li><a href="{% url "users:signup" %}">Signup</a></li>
		{% endif %}
	</ul>
</header>

alextube_practice0/alextube/alextube/templates/partials/messages.html
{% if messages %}
<section id="messages">
	<ul>
	{% for message in messages %}
	    <li class="{{ message.tags }}">{{ message }}</li>
	{% endfor %}
	</ul>
</section>
{% endif %}

alextube_practice0/alextube/posts/templates/posts/confirm.html
{% extends "base.html" %}


{% block content %}
<h1>Confirm Post</h1>

<iframe src="{{ youtube_embed_url }}"></iframe>
<h3>{{ title }}</h3>
<p>{{ content }}</p>

<a href="{{ youtube_original_url }}" target="_blank">Watch this video at Youtube</a>

<form action="{% url "posts:create" %}" method="POST">
	<p> Do you want to post with this content? </p>
	{% csrf_token %}
	<input type="hidden" name="title" value="{{ title }}">
	<input type="hidden" name="video_id" value="{{ video_id }}">
	<input type="hidden" name="content" value="{{ content }}">
	<input type="submit" name="Confirm and Post">
</form>

{% endblock %}

alextube_practice0/alextube/posts/templates/posts/new.html
{% extends "base.html" %}


{% block content %}
<section>
	<form action="{% url "posts:confirm" %}" method="POST">
		{% csrf_token %}
		<input type="text" name="title" placeholder="Title">
		<input type="text" name="video_id" placeholder="Youtube Video ID">
		<textarea name="content" placeholder="Content"></textarea>
		<input type="submit" value="Post">
	</form>
</section>
{% endblock %}

alextube_practice0/alextube/users/templates/users/login.html
{% extends "base.html" %}


{% block content %}
<h1>Login</h1>
<section>
<form action="{% url "users:login" %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="next_url" value="{{ request.GET.next }}">
	<input type="text" name="username" placeholder="username" required>
	<input type="password" name="password"  placeholder="password" required>
	<input type="submit" value="Login">
</form>
</section>

<section>
	<ul>
		<li>
			<a href="{% url "social:begin" backend="facebook" %}">Login with Facebook</a>
		</li>
		<li>
			<a href="{% url "social:begin" backend="kakao" %}">Login with Kakaotalk</a>
		</li>
	</ul>
</section>
{% endblock %}

alextube_practice0/alextube/users/templates/users/signup.html
{% extends "base.html" %}


{% block content %}
<h1>Signup</h1>
<section>
	<form action="{% url "users:signup" %}" method="POST">
        {% csrf_token %}
	<input type="text" name="username" placeholder="username" required>
	<input type="password" name="password"  placeholder="password" required>
	<input type="text" name="phonenumber"  placeholder="phonenumber">
	<input type="submit" value="signup">
</form>
</section>

<section>
	<ul>
		<li>
			<a href="{% url "social:begin" backend="facebook" %}">Signup with Facebook</a>
		</li>
		<li>
			<a href="{% url "social:begin" backend="kakao" %}">Signup with Kakaotalk</a>
		</li>
	</ul>
</section>

{% endblock %}